fix error remove unused variable
/home/travis/build/milestorme/azerothcore-wotlk/modules/mod-premium/src/Npc_Services.cpp:58:36: fatal error: unused variable 'ttr' [-Wunused-variable]
                            uint32 ttr = (resetTime >= time(nullptr) ? resetTime - time(nullptr) : 0);
                                      ^
1 error generated.